const themes = {
    snow: {
      backgroundImage: 'snow.webp',
      textColor: '#000000',
      inputBackgroundColor: '#ffffff',
      buttonImage: '/button.svg',
      buttonHoverImage: '/button.svg',
    },
    mist: {
      backgroundImage: 'mist.webp',
      textColor: '#e0e0e0',
      inputBackgroundColor: '#333333',
      buttonImage: '/button.svg',
      buttonHoverImage: '/button.svg',
    },
    zen: {
        backgroundImage: 'zen.webp',
        textColor: '#e0e0e0',
        inputBackgroundColor: '#333333',
        buttonImage: '/button.svg',
        buttonHoverImage: '/button.svg',
      },
    tao: {
        backgroundImage: 'tao.webp',
        textColor: '#e0e0e0',
        inputBackgroundColor: '#333333',
        buttonImage: '/button.svg',
        buttonHoverImage: '/button.svg',
    },
    default: {
      textColor: '#d4d4d4',
      inputBackgroundColor: '#292929',
      buttonImage: '/button.svg',
      buttonHoverImage: '/button2.svg',
    },
    stillness: {
      backgroundImage: 'images/stillness.webp',
      mobileBackgroundImage: 'images/stillness-m.webp',
      textColor: '#d4d4d4',
      inputBackgroundColor: '#292929',
      buttonImage: '/button.svg',
      buttonHoverImage: '/button2.svg',
    },
    mountains: {
      backgroundImage: 'images/mountains.webp',
      mobileBackgroundImage: 'images/mountains-m.webp',
      textColor: '#d4d4d4',
      inputBackgroundColor: '#292929',
      buttonImage: '/button.svg',
      buttonHoverImage: '/button2.svg',
    },
    essence: {
      backgroundImage: 'images/essence.webp',
      mobileBackgroundImage: 'images/essence-m.webp',
      textColor: '#d4d4d4',
      inputBackgroundColor: '#292929',
      buttonImage: '/button.svg',
      buttonHoverImage: '/button2.svg',
    },
    tao: {
      backgroundImage: 'images/tao.webp',
      mobileBackgroundImage: 'images/tao-m.webp',
      textColor: '#d4d4d4',
      inputBackgroundColor: '#292929',
      buttonImage: '/button.svg',
      buttonHoverImage: '/button2.svg',
    },
    zen: {
      backgroundImage: 'images/zen.webp',
      mobileBackgroundImage: 'images/zen-m.webp',
      textColor: '#d4d4d4',
      inputBackgroundColor: '#292929',
      buttonImage: '/button.svg',
      buttonHoverImage: '/button2.svg',
    },
    snow: {
      backgroundImage: 'images/snow.webp',
      mobileBackgroundImage: 'images/snow-m.webp',
      textColor: '#d4d4d4',
      inputBackgroundColor: '#292929',
      buttonImage: '/button.svg',
      buttonHoverImage: '/button2.svg',
    },
    void: {
      backgroundImage: 'images/void.webp',
      mobileBackgroundImage: 'images/void-m.webp',
      textColor: '#d4d4d4',
      inputBackgroundColor: '#292929',
      buttonImage: '/button.svg',
      buttonHoverImage: '/button2.svg',
    },
  };
  
  export default themes;